function BK
%BK Scrollable MATLAB frontend for vehicle plate extraction.

    appFolder = fileparts(mfilename('fullpath'));
    if ~contains(path, appFolder)
        addpath(appFolder);
    end

    buildFrontend();
end

function app = buildFrontend()
    screenSize = get(groot, 'ScreenSize');
    windowWidth = min(1480, screenSize(3) - 80);
    windowHeight = min(900, screenSize(4) - 80);
    left = max(30, floor((screenSize(3) - windowWidth) / 2));
    bottom = max(30, floor((screenSize(4) - windowHeight) / 2));

    fig = uifigure( ...
        'Name', 'Vehicle Plate Detection Frontend', ...
        'Position', [left bottom windowWidth windowHeight], ...
        'Color', [0.95 0.96 0.98]);

    mainPanel = uipanel(fig, ...
        'Position', [0 0 windowWidth windowHeight], ...
        'BorderType', 'none', ...
        'BackgroundColor', [0.95 0.96 0.98], ...
        'Scrollable', 'on');

    contentWidth = windowWidth - 30;
    contentHeight = 1340;

    app = struct();
    app.Figure = fig;
    app.MainPanel = mainPanel;
    app.RootDir = fileparts(fileparts(mfilename('fullpath')));
    app.ImagePath = "";
    app.OriginalImage = [];
    app.Result = [];

    app.HeaderCard = uipanel(mainPanel, ...
        'Position', [15 contentHeight - 165 contentWidth 140], ...
        'BackgroundColor', [0.98 0.99 1.00], ...
        'BorderType', 'line', ...
        'HighlightColor', [0.84 0.87 0.92]);

    app.Title = uilabel(app.HeaderCard, ...
        'Position', [24 78 600 40], ...
        'Text', 'Vehicle Car Plate Extraction', ...
        'FontSize', 28, ...
        'FontWeight', 'bold', ...
        'FontColor', [0.12 0.16 0.22]);

    app.Subtitle = uilabel(app.HeaderCard, ...
        'Position', [24 48 820 24], ...
        'Text', 'Upload a vehicle image, run plate detection, and review the extracted result in a cleaner workflow.', ...
        'FontSize', 13, ...
        'FontColor', [0.36 0.40 0.46]);

    app.UploadButton = uibutton(app.HeaderCard, 'push', ...
        'Text', 'Upload Image', ...
        'Position', [24 12 150 32], ...
        'ButtonPushedFcn', @onUploadImage, ...
        'BackgroundColor', [0.16 0.43 0.84], ...
        'FontColor', [1 1 1], ...
        'FontWeight', 'bold');

    app.ExtractButton = uibutton(app.HeaderCard, 'push', ...
        'Text', 'Extract Plate', ...
        'Position', [188 12 150 32], ...
        'ButtonPushedFcn', @onExtractPlate, ...
        'Enable', 'off', ...
        'BackgroundColor', [0.14 0.63 0.34], ...
        'FontColor', [1 1 1], ...
        'FontWeight', 'bold');

    app.ClearButton = uibutton(app.HeaderCard, 'push', ...
        'Text', 'Clear', ...
        'Position', [352 12 100 32], ...
        'ButtonPushedFcn', @onClearView, ...
        'BackgroundColor', [0.94 0.95 0.97], ...
        'FontColor', [0.20 0.23 0.28]);

    app.ReportButton = uibutton(app.HeaderCard, 'push', ...
        'Text', 'Detailed Report', ...
        'Position', [466 12 140 32], ...
        'ButtonPushedFcn', @onOpenDetailedReport, ...
        'Enable', 'off', ...
        'BackgroundColor', [0.94 0.95 0.97], ...
        'FontColor', [0.20 0.23 0.28]);

    app.ExportReportButton = uibutton(app.HeaderCard, 'push', ...
        'Text', 'Export Report', ...
        'Position', [620 12 140 32], ...
        'ButtonPushedFcn', @onExportDetailedReport, ...
        'Enable', 'off', ...
        'BackgroundColor', [0.94 0.95 0.97], ...
        'FontColor', [0.20 0.23 0.28]);

    app.PathLabel = uilabel(mainPanel, ...
        'Position', [24 contentHeight - 205 contentWidth - 48 24], ...
        'Text', 'Selected image: none', ...
        'FontSize', 12, ...
        'FontColor', [0.28 0.31 0.36]);

    app.StatusLabel = uilabel(mainPanel, ...
        'Position', [24 contentHeight - 236 contentWidth - 48 24], ...
        'Text', 'Status: waiting for image', ...
        'FontSize', 12, ...
        'FontColor', [0.40 0.44 0.50]);

    leftWidth = floor(contentWidth * 0.64);
    rightLeft = 15 + leftWidth + 20;
    rightWidth = contentWidth - leftWidth - 35;

    app.MainCard = uipanel(mainPanel, ...
        'Title', 'Vehicle Preview', ...
        'Position', [15 420 leftWidth 650], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.MainAxes = uiaxes(app.MainCard, ...
        'Position', [18 18 leftWidth - 36 595], ...
        'Box', 'on');
    title(app.MainAxes, 'Vehicle Image');
    axis(app.MainAxes, 'off');

    app.ResultCard = uipanel(mainPanel, ...
        'Title', 'Detected Plate Number', ...
        'Position', [rightLeft 930 rightWidth 140], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.ResultValue = uilabel(app.ResultCard, ...
        'Position', [20 62 rightWidth - 40 40], ...
        'Text', 'Not detected yet', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 26, ...
        'FontWeight', 'bold', ...
        'FontColor', [0.14 0.18 0.24]);

    app.ResultHint = uilabel(app.ResultCard, ...
        'Position', [20 28 rightWidth - 40 24], ...
        'Text', 'A reliable OCR result will appear here after extraction.', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 12, ...
        'FontColor', [0.42 0.46 0.52]);

    app.SummaryCard = uipanel(mainPanel, ...
        'Title', 'Detection Summary', ...
        'Position', [rightLeft 760 rightWidth 145], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.SummaryText = uitextarea(app.SummaryCard, ...
        'Position', [14 14 rightWidth - 28 100], ...
        'Editable', 'off', ...
        'FontSize', 13, ...
        'Value', {'Detection summary will appear here.'});

    app.PlateCard = uipanel(mainPanel, ...
        'Title', 'Detected Plate Region', ...
        'Position', [rightLeft 505 rightWidth 225], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.PlateAxes = uiaxes(app.PlateCard, ...
        'Position', [14 14 rightWidth - 28 180], ...
        'Box', 'on');
    title(app.PlateAxes, 'Plate Crop');
    axis(app.PlateAxes, 'off');

    app.BinaryCard = uipanel(mainPanel, ...
        'Title', 'Plate Evidence', ...
        'Position', [rightLeft 250 rightWidth 225], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.BinaryAxes = uiaxes(app.BinaryCard, ...
        'Position', [14 14 rightWidth - 28 180], ...
        'Box', 'on');
    title(app.BinaryAxes, 'Binary Evidence');
    axis(app.BinaryAxes, 'off');

    app.InfoCard = uipanel(mainPanel, ...
        'Title', 'Session Notes', ...
        'Position', [15 205 contentWidth 190], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.InfoText = uitextarea(app.InfoCard, ...
        'Position', [14 14 contentWidth - 28 145], ...
        'Editable', 'off', ...
        'FontSize', 13, ...
        'Value', { ...
            'How to use:', ...
            '1. Click Upload Image.', ...
            '2. Choose a vehicle image.', ...
            '3. Click Extract Plate to run the current MATLAB method.', ...
            '4. Scroll to review the crop, binary evidence, and result summary.'});

    app.MethodCard = uipanel(mainPanel, ...
        'Title', 'Current Detection Method', ...
        'Position', [15 15 contentWidth 165], ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.98 0.99 1.00]);

    app.MethodText = uitextarea(app.MethodCard, ...
        'Position', [14 14 contentWidth - 28 120], ...
        'Editable', 'off', ...
        'FontSize', 12, ...
        'Value', { ...
            'Method summary:', ...
            'This version uses a fallback MATLAB pipeline with a new grouped-text detector first.', ...
            '1. Try detector v4 first using character grouping and OCR on the strongest plate band.', ...
            '2. Accept the result only if OCR contains both letters and numbers in a plate-like Malaysian pattern.', ...
            '3. If v4 fails that check, try v2, then v1.', ...
            '4. If those still fail, use the OCR-first v3 fallback.'});

    guidata(fig, app);

    function onUploadImage(~, ~)
        currentApp = guidata(fig);
        startFolder = fullfile(currentApp.RootDir, 'DataSet', 'images');
        if ~isfolder(startFolder)
            startFolder = pwd;
        end

        [fileName, filePath] = uigetfile( ...
            {'*.jpg;*.jpeg;*.png;*.bmp', 'Image Files (*.jpg, *.jpeg, *.png, *.bmp)'}, ...
            'Select Vehicle Image', ...
            startFolder);

        if isequal(fileName, 0)
            return;
        end

        selectedPath = fullfile(filePath, fileName);
        currentApp.ImagePath = string(selectedPath);
        currentApp.Result = [];

        try
            currentApp.OriginalImage = imread(selectedPath);
            imshow(currentApp.OriginalImage, 'Parent', currentApp.MainAxes);
            title(currentApp.MainAxes, 'Vehicle Image');
            cla(currentApp.PlateAxes);
            title(currentApp.PlateAxes, 'Plate Crop');
            cla(currentApp.BinaryAxes);
            title(currentApp.BinaryAxes, 'Binary Evidence');

            currentApp.PathLabel.Text = ['Selected image: ' selectedPath];
            currentApp.StatusLabel.Text = 'Status: image loaded, ready for extraction';
            currentApp.ResultValue.Text = 'Ready to extract';
            currentApp.ResultValue.FontColor = [0.14 0.18 0.24];
            currentApp.ResultHint.Text = 'Click Extract Plate to run the current method.';
            currentApp.SummaryText.Value = {'Detection summary will appear here.'};
            currentApp.InfoText.Value = { ...
                'Image loaded successfully.', ...
                'Scroll through the cards to inspect the result after extraction.', ...
                'This UI is using your current classical detector method.'};
            currentApp.ExtractButton.Enable = 'on';
            currentApp.ReportButton.Enable = 'off';
            currentApp.ExportReportButton.Enable = 'off';
        catch readError
            currentApp.StatusLabel.Text = 'Status: failed to load image';
            currentApp.ResultValue.Text = 'Load failed';
            currentApp.ResultValue.FontColor = [0.78 0.20 0.20];
            currentApp.ResultHint.Text = 'Check the selected image file and try again.';
            currentApp.SummaryText.Value = {['Error: ' readError.message]};
            currentApp.ExtractButton.Enable = 'off';
            currentApp.ReportButton.Enable = 'off';
            currentApp.ExportReportButton.Enable = 'off';
        end

        guidata(fig, currentApp);
    end

    function onExtractPlate(~, ~)
        currentApp = guidata(fig);
        if strlength(currentApp.ImagePath) == 0
            uialert(fig, 'Please upload an image first.', 'No Image Selected');
            return;
        end

        currentApp.StatusLabel.Text = 'Status: running fallback plate extraction (v4 -> v2 -> v1 -> v3)...';
        currentApp.ResultValue.Text = 'Processing...';
        currentApp.ResultValue.FontColor = [0.16 0.43 0.84];
        currentApp.ResultHint.Text = 'Please wait while MATLAB analyzes the image.';
        currentApp.ExtractButton.Enable = 'off';
        drawnow;

        try
            result = extractCarPlateFromImage(char(currentApp.ImagePath));
            currentApp.Result = result;
            showDetectionResult(currentApp, result);
            currentApp.StatusLabel.Text = 'Status: extraction completed';
            if hasDetailedReport(result)
                currentApp.ReportButton.Enable = 'on';
                currentApp.ExportReportButton.Enable = 'on';
            end
        catch extractionError
            currentApp.StatusLabel.Text = 'Status: extraction failed';
            currentApp.ResultValue.Text = 'Extraction failed';
            currentApp.ResultValue.FontColor = [0.78 0.20 0.20];
            currentApp.ResultHint.Text = 'The fallback pipeline could not finish cleanly.';
            currentApp.SummaryText.Value = {['Error: ' extractionError.message]};
            currentApp.InfoText.Value = { ...
                'The pipeline could not finish.', ...
                'Check that MATLAB OCR and Image Processing Toolbox features are available.', ...
                'Then try another clearer image.'};
            currentApp.ReportButton.Enable = 'off';
            currentApp.ExportReportButton.Enable = 'off';
        end

        currentApp.ExtractButton.Enable = 'on';
        guidata(fig, currentApp);
    end

    function onClearView(~, ~)
        currentApp = guidata(fig);
        currentApp.ImagePath = "";
        currentApp.OriginalImage = [];
        currentApp.Result = [];

        cla(currentApp.MainAxes);
        title(currentApp.MainAxes, 'Vehicle Image');
        cla(currentApp.PlateAxes);
        title(currentApp.PlateAxes, 'Plate Crop');
        cla(currentApp.BinaryAxes);
        title(currentApp.BinaryAxes, 'Binary Evidence');

        currentApp.PathLabel.Text = 'Selected image: none';
        currentApp.StatusLabel.Text = 'Status: waiting for image';
        currentApp.ResultValue.Text = 'Not detected yet';
        currentApp.ResultValue.FontColor = [0.14 0.18 0.24];
        currentApp.ResultHint.Text = 'A reliable OCR result will appear here after extraction.';
        currentApp.SummaryText.Value = {'Detection summary will appear here.'};
        currentApp.InfoText.Value = { ...
            'How to use:', ...
            '1. Click Upload Image.', ...
            '2. Choose a vehicle image.', ...
            '3. Click Extract Plate to run the current MATLAB method.', ...
            '4. Scroll to review the crop, binary evidence, and result summary.'};
        currentApp.ExtractButton.Enable = 'off';
        currentApp.ReportButton.Enable = 'off';
        currentApp.ExportReportButton.Enable = 'off';

        guidata(fig, currentApp);
    end

    function onOpenDetailedReport(~, ~)
        currentApp = guidata(fig);
        if isempty(currentApp.Result) || ~hasDetailedReport(currentApp.Result)
            uialert(fig, 'Run plate extraction first to generate the debug report.', 'No Report Available');
            return;
        end

        try
            showDetailedReportWindow(currentApp.Result);
        catch reportError
            warning('PlateReport:OpenFailed', 'Detailed report window failed: %s', reportError.message);
            uialert(fig, sprintf('Could not open the detailed report window.%s%s', ...
                newline, reportError.message), ...
                'Detailed Report Error', 'Icon', 'warning');
        end
    end

    function onExportDetailedReport(~, ~)
        currentApp = guidata(fig);
        if isempty(currentApp.Result) || ~hasDetailedReport(currentApp.Result)
            uialert(fig, 'Run plate extraction first to generate the debug report.', 'No Report Available');
            return;
        end

        try
            exportFolder = exportDetailedReport(currentApp.Result);
            uialert(fig, sprintf('Detailed report saved to:%s%s', newline, exportFolder), ...
                'Report Saved', 'Icon', 'success');
        catch exportError
            warning('PlateReport:ExportFailed', 'Detailed report export failed: %s', exportError.message);
            try
                fallbackFolder = exportDetailedReportFallback(currentApp.Result);
                uialert(fig, sprintf(['Detailed report export hit a graphics issue.%s%s%s' ...
                    'Saved fallback report to:%s%s'], ...
                    newline, exportError.message, newline, newline, fallbackFolder), ...
                    'Report Saved With Fallback', 'Icon', 'warning');
            catch fallbackError
                warning('PlateReport:FallbackExportFailed', ...
                    'Fallback detailed report export failed: %s', fallbackError.message);
                uialert(fig, sprintf(['Detailed report export failed.%s%s%s' ...
                    'Fallback export also failed:%s%s'], ...
                    newline, exportError.message, newline, newline, fallbackError.message), ...
                    'Report Export Error', 'Icon', 'error');
            end
        end
    end
end

function showDetectionResult(app, result)
    imshow(result.Image, 'Parent', app.MainAxes);
    hold(app.MainAxes, 'on');

    if ~isempty(result.PlateBox)
        rectangle(app.MainAxes, ...
            'Position', result.PlateBox, ...
            'EdgeColor', [0.10 0.85 0.35], ...
            'LineWidth', 2.2);

        if result.IsPlateTextValid
            text(app.MainAxes, ...
                result.PlateBox(1), ...
                max(result.PlateBox(2) - 12, 12), ...
                char(result.PlateText), ...
                'Color', 'yellow', ...
                'BackgroundColor', 'black', ...
                'FontSize', 13, ...
                'FontWeight', 'bold', ...
                'Margin', 2);
            title(app.MainAxes, ['Detected Plate: ' char(result.PlateText)]);
        else
            title(app.MainAxes, 'Plate Region Detected');
        end
    else
        for n = 1:size(result.CandidateBoxes, 1)
            rectangle(app.MainAxes, ...
                'Position', result.CandidateBoxes(n, :), ...
                'EdgeColor', [0.93 0.70 0.12], ...
                'LineWidth', 1.2);
        end
        title(app.MainAxes, 'No Reliable Plate Found');
    end

    hold(app.MainAxes, 'off');

    if ~isempty(result.PlateImage)
        imshow(result.PlateImage, 'Parent', app.PlateAxes);
        title(app.PlateAxes, 'Detected Plate Crop');
    else
        cla(app.PlateAxes);
        title(app.PlateAxes, 'Detected Plate Crop');
    end

    if ~isempty(result.BinaryPlate)
        imshow(result.BinaryPlate, 'Parent', app.BinaryAxes);
        title(app.BinaryAxes, 'Binary Plate Evidence');
    else
        cla(app.BinaryAxes);
        title(app.BinaryAxes, 'Binary Plate Evidence');
    end

    if result.IsPlateTextValid
        app.ResultValue.Text = char(result.PlateText);
        app.ResultValue.FontColor = [0.10 0.55 0.30];
        app.ResultHint.Text = ['Accepted from ' char(result.MethodUsed) '.'];
        app.SummaryText.Value = { ...
            'Detected plate text:', ...
            char(result.PlateText), ...
            ['Accepted method: ' char(result.MethodUsed)], ...
            'Review the crop and binary evidence cards below for quality.'};
    elseif ~isempty(result.PlateBox)
        app.ResultValue.Text = 'Low-confidence candidate';
        app.ResultValue.FontColor = [0.86 0.54 0.05];
        if strlength(result.PlateText) > 0
            app.ResultHint.Text = 'Plate candidate found, but OCR is not reliable enough for final acceptance.';
            app.SummaryText.Value = { ...
                'Plate candidate detected.', ...
                ['Low-confidence OCR text: ' char(result.PlateText)], ...
                ['Best fallback method tried: ' char(result.MethodUsed)], ...
                'Inspect the crop and binary evidence before trusting this read.'};
        else
            app.ResultHint.Text = 'A region was found, but none of the fallback OCR results looked plate-like.';
            app.SummaryText.Value = { ...
                'Plate region detected.', ...
                'OCR text is still uncertain for this image.', ...
                ['Best fallback method tried: ' char(result.MethodUsed)], ...
                'Inspect the crop and binary evidence to judge the result.'};
        end
    else
        app.ResultValue.Text = 'No plate detected';
        app.ResultValue.FontColor = [0.78 0.20 0.20];
        app.ResultHint.Text = 'No strong plate candidate matched the current rules.';
        app.SummaryText.Value = { ...
            'No reliable plate region detected.', ...
            'Try another image with a clearer plate area.'};
    end

    app.InfoText.Value = { ...
        ['Methods tried: ' strjoin(cellstr(result.AttemptedMethods), ' -> ')], ...
        ['Candidates checked: ' num2str(size(result.CandidateBoxes, 1))], ...
        'Green rectangle shows the best selected region when available.', ...
        'Plate crop and binary evidence are separated into their own cards for easier review.', ...
        'Use Detailed Report to inspect steps, or Export Report to save them without opening extra UI.'};
end

function tf = hasDetailedReport(result)
    tf = isstruct(result) && isfield(result, 'DebugReport') && ...
        isstruct(result.DebugReport) && isfield(result.DebugReport, 'Attempts') && ...
        ~isempty(result.DebugReport.Attempts);
end

function showDetailedReportWindow(result)
    report = result.DebugReport;
    windowWidth = 1280;
    windowHeight = 820;
    totalHeight = 90;
    cardWidth = 1220;
    for i = 1:numel(report.Attempts)
        stepCount = numel(report.Attempts(i).Steps);
        stepRows = max(1, ceil(stepCount / 2));
        totalHeight = totalHeight + 120 + stepRows * 290 + 20;
    end
    canvasHeight = max(820, totalHeight);

    reportFigure = uifigure( ...
        'Name', 'Plate Detection Detailed Report', ...
        'Position', [80 60 windowWidth windowHeight], ...
        'Color', [0.95 0.96 0.98]);

    scrollPanel = uipanel(reportFigure, ...
        'Position', [0 0 windowWidth windowHeight], ...
        'BorderType', 'none', ...
        'BackgroundColor', [0.95 0.96 0.98], ...
        'Scrollable', 'on');

    headerText = sprintf('Methods tried: %s | Selected: %s', ...
        strjoin(cellstr(report.AttemptedMethods), ' -> '), char(report.SelectedMethod));
    uilabel(scrollPanel, ...
        'Position', [20 canvasHeight - 48 1200 28], ...
        'Text', headerText, ...
        'FontSize', 16, ...
        'FontWeight', 'bold', ...
        'FontColor', [0.12 0.16 0.22]);

    yTop = canvasHeight - 80;

    for i = 1:numel(report.Attempts)
        attempt = report.Attempts(i);
        stepCount = numel(attempt.Steps);
        stepRows = max(1, ceil(stepCount / 2));
        cardHeight = 120 + stepRows * 290;

        card = uipanel(scrollPanel, ...
            'Title', sprintf('Method %s | Status: %s', upper(char(attempt.Method)), char(attempt.Status)), ...
            'Position', [20 yTop - cardHeight cardWidth cardHeight], ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [0.98 0.99 1.00]);

        notesText = char(string(attempt.Notes));
        if strlength(string(attempt.Notes)) == 0
            notesText = 'No additional notes.';
        end

        uilabel(card, ...
            'Position', [14 cardHeight - 48 cardWidth - 28 28], ...
            'Text', notesText, ...
            'FontSize', 12, ...
            'FontColor', [0.36 0.40 0.46]);

        for stepIndex = 1:stepCount
            currentStep = attempt.Steps(stepIndex);
            rowIndex = floor((stepIndex - 1) / 2);
            colIndex = mod(stepIndex - 1, 2);
            panelWidth = floor((cardWidth - 42) / 2);
            stepX = 14 + colIndex * (panelWidth + 14);
            stepY = cardHeight - 90 - (rowIndex + 1) * 270;

            stepPanel = uipanel(card, ...
                'Title', char(currentStep.Title), ...
                'Position', [stepX stepY panelWidth 250], ...
                'BackgroundColor', [1 1 1]);

            stepAxes = uiaxes(stepPanel, ...
                'Position', [10 48 panelWidth - 20 180], ...
                'Box', 'on');
            axis(stepAxes, 'off');

            if ~isempty(currentStep.Image)
                imshow(currentStep.Image, 'Parent', stepAxes);
            else
                title(stepAxes, 'No image available');
            end

            stepDescription = char(string(currentStep.Description));
            uitextarea(stepPanel, ...
                'Position', [10 8 panelWidth - 20 36], ...
                'Editable', 'off', ...
                'Value', {stepDescription}, ...
                'FontSize', 11);
        end

        if stepCount == 0
            uitextarea(card, ...
                'Position', [14 14 cardWidth - 28 cardHeight - 80], ...
                'Editable', 'off', ...
                'Value', {'No intermediate steps were captured for this method.'}, ...
                'FontSize', 12);
        end

        yTop = yTop - cardHeight - 20;
    end
end

function exportFolder = exportDetailedReport(result)
    report = result.DebugReport;
    reportRoot = fullfile(getDefaultDownloadsFolder(), 'PlateDetectionReports');
    if ~isfolder(reportRoot)
        mkdir(reportRoot);
    end

    timestamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    exportFolder = fullfile(reportRoot, ['PlateReport_' char(timestamp)]);
    mkdir(exportFolder);

    for i = 1:numel(report.Attempts)
        attempt = report.Attempts(i);
        methodFolder = fullfile(exportFolder, upper(char(attempt.Method)));
        if ~isfolder(methodFolder)
            mkdir(methodFolder);
        end
        try
            exportMethodReportImage(attempt, methodFolder);
        catch exportError
            warning('PlateReport:MethodExportFailed', ...
                'Method %s report export failed: %s', char(attempt.Method), exportError.message);
            writeAttemptFallbackSummary(attempt, methodFolder, exportError);
        end
    end
end

function exportFolder = exportDetailedReportFallback(result)
    report = result.DebugReport;
    reportRoot = fullfile(getDefaultDownloadsFolder(), 'PlateDetectionReports');
    if ~isfolder(reportRoot)
        mkdir(reportRoot);
    end

    timestamp = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    exportFolder = fullfile(reportRoot, ['PlateReport_Fallback_' char(timestamp)]);
    mkdir(exportFolder);

    for i = 1:numel(report.Attempts)
        attempt = report.Attempts(i);
        methodFolder = fullfile(exportFolder, upper(char(attempt.Method)));
        if ~isfolder(methodFolder)
            mkdir(methodFolder);
        end
        writeAttemptFallbackSummary(attempt, methodFolder, []);
    end
end

function folderPath = getDefaultDownloadsFolder()
    userProfile = getenv('USERPROFILE');
    if ~isempty(userProfile)
        downloadsPath = fullfile(userProfile, 'Downloads');
        if isfolder(downloadsPath)
            folderPath = downloadsPath;
            return;
        end
    end

    folderPath = pwd;
end

function safeName = sanitizeFileName(fileName)
    safeName = regexprep(string(fileName), '[^A-Za-z0-9_-]', '_');
    safeName = regexprep(safeName, '_+', '_');
    safeName = char(safeName);
end

function writableImage = makeWritableImage(imageData)
    if islogical(imageData)
        writableImage = uint8(imageData) * 255;
        return;
    end

    if isa(imageData, 'uint8') || isa(imageData, 'uint16')
        writableImage = imageData;
        return;
    end

    if isfloat(imageData)
        writableImage = im2uint8(mat2gray(imageData));
        return;
    end

    writableImage = im2uint8(imageData);
end

function exportMethodReportImage(attempt, methodFolder)
    stepCount = numel(attempt.Steps);
    stepRows = max(1, ceil(stepCount / 2));
    cardWidth = 1400;
    cardHeight = 240 + stepRows * 340;

    exportFigure = figure( ...
        'Visible', 'off', ...
        'Color', [1 1 1], ...
        'Position', [100 100 cardWidth cardHeight], ...
        'PaperPositionMode', 'auto', ...
        'InvertHardcopy', 'off');

    cleanupFigure = onCleanup(@() close(exportFigure));

    notesText = char(string(attempt.Notes));
    if strlength(string(attempt.Notes)) == 0
        notesText = 'No additional notes.';
    end

    annotation(exportFigure, 'textbox', [0.02 0.965 0.96 0.03], ...
        'String', sprintf('Method %s | Status: %s', upper(char(attempt.Method)), char(attempt.Status)), ...
        'EdgeColor', 'none', 'FontWeight', 'bold', 'FontSize', 13, ...
        'Color', [0.10 0.12 0.16], 'Interpreter', 'none');
    annotation(exportFigure, 'textbox', [0.02 0.935 0.96 0.028], ...
        'String', notesText, ...
        'EdgeColor', 'none', 'FontSize', 11, 'Color', [0.36 0.40 0.46], ...
        'Interpreter', 'none');

    tiled = tiledlayout(exportFigure, stepRows, 2, ...
        'Padding', 'compact', 'TileSpacing', 'compact');

    for stepIndex = 1:stepCount
        currentStep = attempt.Steps(stepIndex);
        ax = nexttile(tiled);
        axis(ax, 'off', 'image');

        if ~isempty(currentStep.Image)
            imageData = makeWritableImage(currentStep.Image);
            imshow(imageData, 'Parent', ax);
        else
            text(ax, 0.5, 0.5, sprintf('No debug image available for Step %d', stepIndex), ...
                'HorizontalAlignment', 'center', 'Units', 'normalized', ...
                'Color', [0.25 0.25 0.25], 'FontSize', 11);
        end

        title(ax, char(string(currentStep.Title)), 'Interpreter', 'none', 'FontSize', 11);
        descText = char(string(currentStep.Description));
        if strlength(string(currentStep.Description)) == 0
            descText = 'No description available.';
        end
        text(ax, 0.02, 0.02, descText, ...
            'Units', 'normalized', ...
            'Interpreter', 'none', ...
            'FontSize', 9, ...
            'Color', [0.20 0.20 0.20], ...
            'BackgroundColor', [1 1 1], ...
            'Margin', 2, ...
            'VerticalAlignment', 'bottom', ...
            'HorizontalAlignment', 'left');
    end

    drawnow;
    pause(0.1);

    methodName = upper(char(attempt.Method));
    reportImagePath = fullfile(methodFolder, sprintf('%s_report.png', methodName));
    reportPdfPath = fullfile(methodFolder, sprintf('%s_report.pdf', methodName));
    exportgraphics(exportFigure, reportImagePath, 'Resolution', 200);
    exportgraphics(exportFigure, reportPdfPath, 'ContentType', 'image');
end

function writeAttemptFallbackSummary(attempt, methodFolder, exportError)
    summaryPath = fullfile(methodFolder, 'report_summary.txt');
    fid = fopen(summaryPath, 'w');
    if fid == -1
        return;
    end
    cleanupFile = onCleanup(@() fclose(fid));

    fprintf(fid, 'Method: %s\n', upper(char(attempt.Method)));
    fprintf(fid, 'Status: %s\n', char(string(attempt.Status)));
    fprintf(fid, 'Notes: %s\n', char(string(attempt.Notes)));
    if ~isempty(exportError)
        fprintf(fid, 'Export error: %s\n', exportError.message);
    end
    fprintf(fid, '\nSteps:\n');

    for i = 1:numel(attempt.Steps)
        currentStep = attempt.Steps(i);
        fprintf(fid, '%d. %s\n', i, char(string(currentStep.Title)));
        fprintf(fid, '   %s\n', char(string(currentStep.Description)));
    end

    clear cleanupFile;
end
